### ISSUE TITLE
.rdupe command resulting in “where’s donkey ?” Error message

### ISSUE THREAD

**Issue by MonoprongedFork** [anOtherAnalyse/FamilyFunPack#19]
Hello, sorry to bother you but after several uses of the .rdupe command with a saddled horse on 9b9t, the command will stop mounting me on the horse despite standing within 2 blocks of the horse and instead results in the error message “[FFP] where’s donkey ?” Thank you for your time.

**Comment by anOtherAnalyse** [comment]
Actually you can use a horse as a ride. In the init stage (first time you type '.rdupe') it will look for a horse/donkey/llama and say 'where's your ride' if none found. the 'where's donkey' message should be when typing 'rdupe' a second time next to a donkey/llama for duping. This may have happen because you typed '.rdupe' once and did not finish the procedure. Try using '.rdupe reset' to reset the command, disable packet canceling and start over.
